### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [Pyenb/Pi-hole-blocklist#1]
[i] Target: https://raw.githubusercontent.com/Pyenb/Pi-hole-blocklist/main/blocklist.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 2414525 exact domains and 0 ABP-style domains (ignored 18 non-domain entries)
      Sample of non-domain entries:
        - "disconnect"
        - "arathorn-inkasso"
        - "182.116.104.6"
        - "xiaoqiang"
        - "gatetocontentcom$"

**Comment by Pyenb** [comment]
I think only 18 non-domain entries is acceptable out of 2414525 domains. But still, I will look into it, as these shouldn't have gone trough
